package com.egamboau.gameboy.cpu.instructions;

public enum AddressMode {
    DATA_16_BITS_TO_REGISTER,
    DATA_8_BIT_TO_REGISTER,
    MEMORY_ADDRESS_REGISTER_INCREMENT_TO_REGISTER,
    MEMORY_ADDRESS_REGISTER_TO_REGISTER,
    REGISTER_8_BIT,
    REGISTER_TO_MEMORY_ADDRESS_DATA,
    REGISTER_TO_MEMORY_ADDRESS_REGISTER,REGISTER_16_BIT,
    REGISTER_TO_REGISTER,

}
